### PR TITLE
update build workflow for GitHub Actions

### PR DESCRIPTION
**Pull request by doutori**
## Todo

- Add workflow to push docker images to AWS ECR by using GitHub Actions

## Remark
- `Pushing to ECR` workflows don't work parallel.
  - maybe, workflow files needs to be separated.

## Relations

#78

### CODE REVIEW

**Comment by doutori** [comment]
It seems better to split files to run in parallel...
but I wonder if we need to do that.

**Comment by uruha** [comment]
In the first place, is it necessary to process ECR on the github actions side? .. .. (； ･ `Д ･ ´)

**Comment by doutori** [comment]
It is not always necessary. This is one of the options.

**Comment by uruha** [comment]
LGTM

**Comment by doutori** [comment]
I will write a comment later in the Readme.

**Comment by uruha** [comment]
@doutori thanks !

**Pull request merged**
